name: Run Jest testing suite
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

env:
  NODE_ENV: "test"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build & Run test suite
        run: |
          yarn && yarn build 
          yarn test | tee ./coverage.txt && exit ${PIPESTATUS[0]}
      - name: Jest Coverage Comment
        # Ensures this step is run even on previous step failure (e.g. test failed)
        if: always()
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: coverage/coverage-summary.json
          junitxml-path: junit.xml
          junitxml-title: JUnit
          coverage-path: ./coverage.txt
