name: Enforce kebab-case

on:
  push:
  pull_request:

jobs:
  check-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check For Non Kebab-Cased TypeScript Files
        run: .github/workflows/scripts/kebab-case.sh
